name: build

on:
  push:
    branches:
    - 'main'
jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        PYTHON_VERSION:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
          - 3.11
          - 3.12
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image and push to Docker Hub
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --build-arg FROM_TAG=${{ matrix.PYTHON_VERSION }}  -q --push . -t opaoz/python-base:${{ matrix.PYTHON_VERSION }}